--Pregunta 1
CREATE TABLE ET_USUARIO( ID_USUARIO NUMBER PRIMARY KEY,
USUARIO VARCHAR2(30 BYTE) NOT NULL,
CLAVE VARCHAR2(30 BYTE) NOT NULL,
ESTADO CHAR(1) NOT NULL);


--Pregunta 2
COMMENT ON COLUMN ET_USUARIO.ID_USUARIO IS 'Identificador del usuario.';
COMMENT ON COLUMN ET_USUARIO.USUARIO IS 'Nombre de usuario.';
COMMENT ON COLUMN ET_USUARIO.CLAVE IS 'Clave o contrasenha.';
COMMENT ON COLUMN ET_USUARIO.ESTADO IS 'A: activo I: inactivo.';


--Pregunta 3
CREATE TABLE ET_ROL( ID_ROL NUMBER PRIMARY KEY,
NOMBRE VARCHAR2(30 BYTE) NOT NULL);

--Pregunta 4
COMMENT ON COLUMN ET_ROL.ID_ROL IS 'Identificador de rol';
COMMENT ON COLUMN ET_ROL.NOMBRE IS 'Nombre del rol';

--Pregunta 5
ALTER TABLE ET_USUARIO ADD( ID_ROL NUMBER NOT NULL);

--Pregunta 6
ALTER TABLE ET_USUARIO ADD CONSTRAINT fk_id_rol FOREIGN KEY (ID_ROL)
REFERENCES ET_ROL(ID_ROL);

--Pregunta 7
INSERT INTO ET_ROL(ID_ROL, NOMBRE) VALUES (1,'Admin');
INSERT INTO ET_ROL(ID_ROL, NOMBRE) VALUES (2,'Conductor');
INSERT INTO ET_ROL(ID_ROL, NOMBRE) VALUES (3,'Boleteria');

--Pregunta 8
INSERT INTO ET_USUARIO(ID_USUARIO, USUARIO, CLAVE, ESTADO, ID_ROL) VALUES
(1, 'aangeles', '1234', 'A', 1);
INSERT INTO ET_USUARIO(ID_USUARIO, USUARIO, CLAVE, ESTADO, ID_ROL) VALUES
(2, 'dpaz', '1234', 'A', 2);
INSERT INTO ET_USUARIO(ID_USUARIO, USUARIO, CLAVE, ESTADO, ID_ROL) VALUES
(3, 'jpauca', '1234', 'A', 2);
INSERT INTO ET_USUARIO(ID_USUARIO, USUARIO, CLAVE, ESTADO, ID_ROL) VALUES
(4, 'ldiaz', '1234', 'A', 3);
INSERT INTO ET_USUARIO(ID_USUARIO, USUARIO, CLAVE, ESTADO, ID_ROL) VALUES
(5, 'elozano', '1234', 'A', 3);

--Pregunta 9
ALTER TABLE ET_TICKET RENAME COLUMN ID_TICKET_VIAJE TO ID_TICKET;
ALTER TABLE ET_TURNO RENAME COLUMN ID_TURNO_VIAJE TO ID_TURNO;

--Pregunta 10
ALTER TABLE ET_CONDUCTOR MODIFY( APELLIDO_PATERNO VARCHAR2(50 BYTE),
APELLIDO_MATERNO VARCHAR2(50 BYTE));


ALTER TABLE ET_MODELO_BUS MODIFY FABRICANTE VARCHAR2(100 BYTE);

--Pregunta 11
UPDATE ET_BUS SET ESTADO = 'M' WHERE ID_BUS = 5 AND ESTADO = 'A';

--Pregunta 12
UPDATE ET_MODELO_BUS SET FABRICANTE = 'Mercedes Benz' WHERE 
FABRICANTE = 'Mercedes';

--Pregunta 13
SELECT * FROM ET_CONDUCTOR WHERE TIPO_LICENCIA = 'A-IIIa';
SELECT * FROM ET_MODELO_BUS WHERE NUMERO_ASIENTOS >= 60;

--Pregunta 14
SELECT * FROM ET_BUS WHERE PLACA LIKE 'M%';
SELECT * FROM ET_PARADERO WHERE ID_DISTRITO IN 
    (SELECT ID_DISTRITO FROM ET_DISTRITO WHERE UPPER(NOMBRE) = 'MIRAFLORES');





