--PREGUNTA 1
SELECT ID_MODELO_BUS, MODELO, NUMERO_ASIENTOS, CAPACIDAD_DE_PIE,
    NUMERO_ASIENTOS + CAPACIDAD_DE_PIE AS "CAPACIDAD_TOTAL" 
    FROM ET_MODELO_BUS
    ORDER BY CAPACIDAD_TOTAL ASC;
    
--PREGUNTA 2
SELECT ID_BUS, FECHA, SENTIDO, COUNT(*) AS "CANTIDAD" FROM ET_TURNO
    GROUP BY ID_BUS, FECHA, SENTIDO
    ORDER BY ID_BUS ASC;
    
--PREGUNTA 3
SELECT D.NOMBRE, 
    REPLACE(REPLACE(REPLACE(P.ESTADO, 'B', 'dado de baja'),'A', 'actualmente se usa'),'T', 'paradero reubicado temporalmente') AS "ESTADO_PARADERO", 
    COUNT(P.TIPO)
    FROM ET_PARADERO P, ET_DISTRITO D
    WHERE D.ID_DISTRITO = P.ID_DISTRITO
    GROUP BY D.NOMBRE, P.ESTADO
    ORDER BY 1, 3 DESC, 2 ASC;
    
--PREGUNTA 4
SELECT T.ID_BUS, T.FECHA, T.ID_TURNO_VIAJE,
    CASE 
    WHEN T.SENTIDO='I' THEN 'Ida'
    WHEN T.SENTIDO='V' THEN 'Vuelta'
    END AS SENTIDO, SUM(P.PASAJEROS_SUBIDA) AS "CANTIDAD_PASAJEROS" FROM ET_TURNO T, ET_TURNO_PARADERO P
    WHERE P.ID_TURNO = T.ID_TURNO_VIAJE
    GROUP BY T.ID_BUS, T.FECHA, T.ID_TURNO_VIAJE, T.SENTIDO
    ORDER BY T.ID_BUS, T.FECHA;
    
--PREGUNTA 5
SELECT DISTINCT P.NOMBRE, TP.PASAJEROS_SUBIDA,TP.PASAJEROS_BAJADA,
        PASAJEROS_SUBIDA + PASAJEROS_BAJADA AS "TOTAL PASAJEROS"
        FROM ET_TURNO_PARADERO TP, ET_PARADERO P WHERE TP.ID_PARADERO = P.ID_PARADERO 
        ORDER BY 4 DESC;

--PREGUNTA 6
SELECT T.SENTIDO, P.NOMBRE, P.TIPO FROM ET_TURNO T, ET_PARADERO P
    WHERE(
    (P.ESTADO = 'A' OR P.ESTADO = 'T')
    AND
    T.FECHA IN(
        SELECT MAX(FECHA)
        FROM ET_TURNO)
    AND 
    T.HORA_PARTIDA IN (
        SELECT MAX(HORA_PARTIDA)
        FROM ET_TURNO)
    )
    GROUP BY T.SENTIDO, P.NOMBRE, P.TIPO
    ORDER BY T.SENTIDO, P.NOMBRE, P.TIPO;

--PREGUNTA 7
SELECT C.NOMBRES||' '||C.APELLIDO_PATERNO||' '||C.APELLIDO_MATERNO,
COUNT(*)
FROM ET_TURNO T, ET_CONDUCTOR C WHERE T.ID_CONDUCTOR = C.ID_CONDUCTOR
GROUP BY C.NOMBRES, C.APELLIDO_PATERNO, C.APELLIDO_MATERNO
ORDER BY 2 ASC;


